package org.cagrid.gme.service.globus;

import java.rmi.RemoteException;

import org.cagrid.gme.service.GlobalModelExchangeImpl;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the GlobalModelExchangeImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class GlobalModelExchangeProviderImpl{
	
	GlobalModelExchangeImpl impl;
	
	public GlobalModelExchangeProviderImpl() throws RemoteException {
		impl = new GlobalModelExchangeImpl();
	}
	

    public org.cagrid.gme.stubs.PublishSchemasResponse publishSchemas(org.cagrid.gme.stubs.PublishSchemasRequest params) throws RemoteException {
    org.cagrid.gme.stubs.PublishSchemasResponse boxedResult = new org.cagrid.gme.stubs.PublishSchemasResponse();
    impl.publishSchemas(params.getSchemas().getXMLSchema());
    return boxedResult;
  }

}
