package gov.nih.nci.cagrid.gridgrouper.service;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 *  @created by Introduce Toolkit version 1.0
 * 
 */
public class ServiceConfiguration {
	

	
}
