package gov.nih.nci.cagrid.annualdemo.service.globus;

import gov.nih.nci.cagrid.annualdemo.service.MageTranslationServicesImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the MageTranslationServicesImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class MageTranslationServicesProviderImpl{
	
	MageTranslationServicesImpl impl;
	
	public MageTranslationServicesProviderImpl() throws RemoteException {
		impl = new MageTranslationServicesImpl();
	}
	

	public gov.nih.nci.cagrid.annualdemo.stubs.BioAssayToStatMLResponse bioAssayToStatML(gov.nih.nci.cagrid.annualdemo.stubs.BioAssayToStatMLRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizeBioAssayToStatML();
		gov.nih.nci.cagrid.annualdemo.stubs.BioAssayToStatMLResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.BioAssayToStatMLResponse();
		boxedResult.setData(impl.bioAssayToStatML(params.getMeasuredBioAssay().getMeasuredBioAssay()));
		return boxedResult;
	}

	public gov.nih.nci.cagrid.annualdemo.stubs.BioAssayToMicroArraySetResponse bioAssayToMicroArraySet(gov.nih.nci.cagrid.annualdemo.stubs.BioAssayToMicroArraySetRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizeBioAssayToMicroArraySet();
		gov.nih.nci.cagrid.annualdemo.stubs.BioAssayToMicroArraySetResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.BioAssayToMicroArraySetResponse();
		boxedResult.setData(impl.bioAssayToMicroArraySet(params.getMeasuredBioAssay().getMeasuredBioAssay()));
		return boxedResult;
	}

	public gov.nih.nci.cagrid.annualdemo.stubs.MageToMicroArraySetResponse mageToMicroArraySet(gov.nih.nci.cagrid.annualdemo.stubs.MageToMicroArraySetRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizeMageToMicroArraySet();
		gov.nih.nci.cagrid.annualdemo.stubs.MageToMicroArraySetResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.MageToMicroArraySetResponse();
		boxedResult.setMicroarraySet(impl.mageToMicroArraySet(params.getCQLQueryResultCollection().getCQLQueryResultCollection()));
		return boxedResult;
	}

	public gov.nih.nci.cagrid.annualdemo.stubs.MageToStatMLResponse mageToStatML(gov.nih.nci.cagrid.annualdemo.stubs.MageToStatMLRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizeMageToStatML();
		gov.nih.nci.cagrid.annualdemo.stubs.MageToStatMLResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.MageToStatMLResponse();
		boxedResult.setData(impl.mageToStatML(params.getCQLQueryResultCollection().getCQLQueryResultCollection()));
		return boxedResult;
	}

	public gov.nih.nci.cagrid.annualdemo.stubs.GwClusterToTreeViewResponse gwClusterToTreeView(gov.nih.nci.cagrid.annualdemo.stubs.GwClusterToTreeViewRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizeGwClusterToTreeView();
		gov.nih.nci.cagrid.annualdemo.stubs.GwClusterToTreeViewResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.GwClusterToTreeViewResponse();
		boxedResult.setTreeViewInputElement(impl.gwClusterToTreeView(params.getHierarchicalCluster().getHierarchicalCluster(),params.getMicroarraySet().getMicroarraySet()));
		return boxedResult;
	}

	public gov.nih.nci.cagrid.annualdemo.stubs.StatmlToMicroarraySetResponse statmlToMicroarraySet(gov.nih.nci.cagrid.annualdemo.stubs.StatmlToMicroarraySetRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizeStatmlToMicroarraySet();
		gov.nih.nci.cagrid.annualdemo.stubs.StatmlToMicroarraySetResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.StatmlToMicroarraySetResponse();
		boxedResult.setMicroarraySet(impl.statmlToMicroarraySet(params.getData().getData()));
		return boxedResult;
	}

	public gov.nih.nci.cagrid.annualdemo.stubs.GpClusterToTreeViewResponse gpClusterToTreeView(gov.nih.nci.cagrid.annualdemo.stubs.GpClusterToTreeViewRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizeGpClusterToTreeView();
		gov.nih.nci.cagrid.annualdemo.stubs.GpClusterToTreeViewResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.GpClusterToTreeViewResponse();
		boxedResult.setTreeViewInputElement(impl.gpClusterToTreeView(params.getConsensusClusterResultCollection().getConsensusClusterResultCollection(),params.getData().getData()));
		return boxedResult;
	}

	public gov.nih.nci.cagrid.annualdemo.stubs.MicroarraySetToStatmlResponse microarraySetToStatml(gov.nih.nci.cagrid.annualdemo.stubs.MicroarraySetToStatmlRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizeMicroarraySetToStatml();
		gov.nih.nci.cagrid.annualdemo.stubs.MicroarraySetToStatmlResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.MicroarraySetToStatmlResponse();
		boxedResult.setData(impl.microarraySetToStatml(params.getMicroarraySet().getMicroarraySet()));
		return boxedResult;
	}

	public gov.nih.nci.cagrid.annualdemo.stubs.PerformAnalysisResponse performAnalysis(gov.nih.nci.cagrid.annualdemo.stubs.PerformAnalysisRequest params) throws RemoteException {
		MageTranslationServicesAuthorization.authorizePerformAnalysis();
		gov.nih.nci.cagrid.annualdemo.stubs.PerformAnalysisResponse boxedResult = new gov.nih.nci.cagrid.annualdemo.stubs.PerformAnalysisResponse();
		boxedResult.setData(impl.performAnalysis(params.getData().getData(),params.getPreprocessDatasetParameterSet().getPreprocessDatasetParameterSet()));
		return boxedResult;
	}

}
