package gov.nih.nci.cagrid.gts.service.globus;

import gov.nih.nci.cagrid.gts.common.GridTrustServiceI;
import gov.nih.nci.cagrid.gts.service.GridTrustServiceImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class GridTrustServiceProviderImpl{
	
	GridTrustServiceI impl;
	
	public GridTrustServiceProviderImpl() {
		impl = new GridTrustServiceImpl();
	}
	
	public gov.nih.nci.cagrid.gts.stubs.AddTrustedAuthorityResponse addTrustedAuthority(gov.nih.nci.cagrid.gts.stubs.AddTrustedAuthority params) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.GTSInternalFault {
		impl.addTrustedAuthority(params.getTrustedAuthority());
		return new gov.nih.nci.cagrid.gts.stubs.AddTrustedAuthorityResponse();
	}

}
