<definitions name="beans" targetNamespace="gov.nih.nci.cagrid.beans"
    xmlns:tns="gov.nih.nci.cagrid.beans/beans" xmlns="http://schemas.xmlsoap.org/wsdl/">
    <types>
        <schema targetNamespace="gov.nih.nci.cagrid.beans/beans"
            xmlns:tns="gov.nih.nci.cagrid.beans/beans"
            xmlns:introduce="gme://gov.nih.nci.cagrid/1/Introduce"
            xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="gme://gov.nih.nci.cagrid/1/Introduce"
                schemaLocation="./IntroduceService.xsd"/>
        </schema>
    </types>
</definitions>
