package org.cagrid.gme.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class GlobalModelExchangeConfiguration implements ServiceConfiguration {

	public static GlobalModelExchangeConfiguration  configuration = null;

	public static GlobalModelExchangeConfiguration getConfiguration() throws Exception {
		if (GlobalModelExchangeConfiguration.configuration != null) {
			return GlobalModelExchangeConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			GlobalModelExchangeConfiguration.configuration = (GlobalModelExchangeConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return GlobalModelExchangeConfiguration.configuration;
	}
	
	private String etcDirectoryPath;
	
	
	private String schemaPersistenceImplementationClassname;
	
	private String schemaPersistenceImplementationPropertiesFile;
	
	
	public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}

	
	public String getSchemaPersistenceImplementationClassname() {
		return schemaPersistenceImplementationClassname;
	}
	
	
	public void setSchemaPersistenceImplementationClassname(String schemaPersistenceImplementationClassname) {
		this.schemaPersistenceImplementationClassname = schemaPersistenceImplementationClassname;
	}

	
	public String getSchemaPersistenceImplementationPropertiesFile() {
		return ContainerConfig.getBaseDirectory() + File.separator + schemaPersistenceImplementationPropertiesFile;
	}
	
	
	public void setSchemaPersistenceImplementationPropertiesFile(String schemaPersistenceImplementationPropertiesFile) {
		this.schemaPersistenceImplementationPropertiesFile = schemaPersistenceImplementationPropertiesFile;
	}

	
}
