package gov.nih.nci.cagrid.dorian.common;

import java.rmi.RemoteException;

/** 
 *   This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface DorianI {

public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;
public java.lang.String registerWithIdP(gov.nih.nci.cagrid.dorian.idp.bean.Application application) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.InvalidUserPropertyFault ;
public gov.nih.nci.cagrid.dorian.idp.bean.IdPUser[] findIdPUsers(gov.nih.nci.cagrid.dorian.idp.bean.IdPUserFilter filter) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public void updateIdPUser(gov.nih.nci.cagrid.dorian.idp.bean.IdPUser user) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.NoSuchUserFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public void removeIdPUser(java.lang.String userId) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public gov.nih.nci.cagrid.dorian.bean.SAMLAssertion authenticateWithIdP(gov.nih.nci.cagrid.dorian.idp.bean.BasicAuthCredential cred) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public gov.nih.nci.cagrid.dorian.bean.X509Certificate[] createProxy(gov.nih.nci.cagrid.dorian.bean.SAMLAssertion saml,gov.nih.nci.cagrid.dorian.ifs.bean.PublicKey publicKey,gov.nih.nci.cagrid.dorian.ifs.bean.ProxyLifetime lifetime) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.InvalidAssertionFault, gov.nih.nci.cagrid.dorian.stubs.InvalidProxyFault, gov.nih.nci.cagrid.dorian.stubs.UserPolicyFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public gov.nih.nci.cagrid.dorian.bean.X509Certificate getCACertificate() throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault ;
public gov.nih.nci.cagrid.dorian.ifs.bean.TrustedIdP[] getTrustedIdPs() throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public gov.nih.nci.cagrid.dorian.ifs.bean.TrustedIdP addTrustedIdP(gov.nih.nci.cagrid.dorian.ifs.bean.TrustedIdP idp) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.InvalidTrustedIdPFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public void updateTrustedIdP(gov.nih.nci.cagrid.dorian.ifs.bean.TrustedIdP trustedIdP) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.InvalidTrustedIdPFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public void removeTrustedIdP(gov.nih.nci.cagrid.dorian.ifs.bean.TrustedIdP trustedIdP) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.InvalidTrustedIdPFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public gov.nih.nci.cagrid.dorian.ifs.bean.IFSUser[] findIFSUsers(gov.nih.nci.cagrid.dorian.ifs.bean.IFSUserFilter filter) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public void updateIFSUser(gov.nih.nci.cagrid.dorian.ifs.bean.IFSUser user) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.InvalidUserFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public void removeIFSUser(gov.nih.nci.cagrid.dorian.ifs.bean.IFSUser user) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.InvalidUserFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public gov.nih.nci.cagrid.dorian.ifs.bean.IFSUser renewIFSUserCredentials(gov.nih.nci.cagrid.dorian.ifs.bean.IFSUser user) throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.InvalidUserFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;
public gov.nih.nci.cagrid.dorian.ifs.bean.IFSUserPolicy[] getIFSUserPolicies() throws RemoteException, gov.nih.nci.cagrid.dorian.stubs.DorianInternalFault, gov.nih.nci.cagrid.dorian.stubs.PermissionDeniedFault ;

}

