/**
 * 
 */
package org.cagrid.installer.tasks;

import java.io.FileOutputStream;
import java.util.Iterator;
import java.util.Properties;
import java.util.Map.Entry;

import org.cagrid.installer.model.CaGridInstallerModel;
import org.cagrid.installer.steps.Constants;

/**
 * @author <a href="mailto:joshua.phillips@semanticbits.com">Joshua Phillips</a>
 *
 */
public class SaveSettingsTask extends BasicTask {
	
	
	public SaveSettingsTask(String name, String description){
		super(name, description);
	}

	protected Object internalExecute(CaGridInstallerModel model) throws Exception {
		Properties props = new Properties();
		for(Iterator i = model.getStateMap().entrySet().iterator(); i.hasNext();){
			Entry entry = (Entry)i.next();
			if(entry.getKey() instanceof String && entry.getValue() instanceof String){
				props.setProperty((String)entry.getKey(), (String)entry.getValue());
			}
		}
		props.store(new FileOutputStream(model.getProperty(Constants.CAGRID_INSTALLER_PROPERTIES)), "Generated by caGrid Installer at " + System.currentTimeMillis());
		return null;
	}

}
