/**
 * 
 */
package org.cagrid.installer.tasks;

import java.io.FileOutputStream;
import java.util.Iterator;
import java.util.Map;
import java.util.Properties;
import java.util.Map.Entry;

import org.cagrid.installer.steps.Constants;

/**
 * @author <a href="mailto:joshua.phillips@semanticbits.com">Joshua Phillips</a>
 *
 */
public class SaveSettingsTask implements Task {
	
	private String name;
	private String description;
	
	public SaveSettingsTask(String name, String description){
		this.name = name;
		this.description = description;
	}

	/* (non-Javadoc)
	 * @see org.cagrid.installer.tasks.Task#execute(java.util.Map)
	 */
	public Object execute(Map state) throws Exception {
		Properties props = new Properties();
		for(Iterator i = state.entrySet().iterator(); i.hasNext();){
			Entry entry = (Entry)i.next();
			if(entry.getKey() instanceof String && entry.getValue() instanceof String){
				props.setProperty((String)entry.getKey(), (String)entry.getValue());
			}
		}
		props.store(new FileOutputStream((String)state.get(Constants.CAGRID_INSTALLER_PROPERTIES)), "Generated by caGrid Installer at " + System.currentTimeMillis());
		return null;
	}

	/* (non-Javadoc)
	 * @see org.cagrid.installer.tasks.Task#getDescription()
	 */
	public String getDescription() {
		return description;
	}

	/* (non-Javadoc)
	 * @see org.cagrid.installer.tasks.Task#getName()
	 */
	public String getName() {
		return name;
	}

}
