package gov.nih.nci.cagrid.fqp.client;


import java.io.InputStream;
import java.rmi.RemoteException;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.Address;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;
import org.apache.axis.utils.ClassUtils;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.cagrid.fqp.stubs.FQPPortType;
import gov.nih.nci.cagrid.fqp.stubs.service.FQPServiceAddressingLocator;
import gov.nih.nci.cagrid.fqp.common.FQPI;


/**
 * This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 */
public class FQPClient implements FQPI {	
	private GlobusCredential proxy;
	private EndpointReferenceType epr;
	
	static{
		org.globus.axis.util.Util.registerTransport();
	}
	
	public FQPClient(String url) throws MalformedURIException {
		this(url,null);	
	}

	public FQPClient(String url, GlobusCredential proxy) throws MalformedURIException {
	   	this.proxy = proxy;
	   	this.epr = new EndpointReferenceType();
	   	this.epr.setAddress(new Address(url));
	}
	
	public FQPClient(EndpointReferenceType epr) throws MalformedURIException {
	   	this(epr,null);
	}
	
	public FQPClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException {
	   	this.proxy = proxy;
	   	this.epr = epr;
	}

	private FQPPortType getPortType() throws RemoteException {

		FQPServiceAddressingLocator locator = new FQPServiceAddressingLocator();
		// attempt to load our context sensitive wsdd file
		InputStream resourceAsStream = ClassUtils.getResourceAsStream(getClass(), "client-config.wsdd");
		if (resourceAsStream != null) {
			// we found it, so tell axis to configure an engine to use it
			EngineConfiguration engineConfig = new FileProvider(resourceAsStream);
			// set the engine of the locator
			locator.setEngine(new AxisClient(engineConfig));
		}
		FQPPortType port = null;
		try {
			port = locator.getFQPPortTypePort(this.epr);
		} catch (Exception e) {
			throw new RemoteException("Unable to configured porttype:" + e.getMessage(), e);
		}

		return port;
	}
	
	public static void usage(){
		System.out.println(FQPClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  FQPClient client = new FQPClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	

	     public gov.nih.nci.cagrid.cqlresultset.CQLQueryResults processDCQL(gov.nih.nci.cagrid.dcql.DCQLQuery DCQLQuery) throws RemoteException {
               FQPPortType port = this.getPortType();
               org.apache.axis.client.Stub stub = (org.apache.axis.client.Stub) port;

               gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLRequest params = new gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLRequest();
               gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLRequestDCQLQuery DCQLQueryContainer = new gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLRequestDCQLQuery();
               DCQLQueryContainer.setDCQLQuery(DCQLQuery);
               params.setDCQLQuery(DCQLQueryContainer);
               gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLResponse boxedResult = port.processDCQL(params);
               return boxedResult.getCQLQueryResultCollection();

	}


}
