package org.cagrid.gaards.cds.delegated.common;

import java.rmi.RemoteException;

/**
 * Represents a Delegated Credential
 *
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface DelegatedCredentialI {

  /**
   * This method allows an authorized user to get a delegated credential.
   *
   * @param publicKey
   * @throws CDSInternalFault
   *	
   * @throws DelegationFault
   *	
   * @throws PermissionDeniedFault
   *	
   */
  public org.cagrid.gaards.cds.common.CertificateChain getDelegatedCredential(org.cagrid.gaards.cds.common.PublicKey publicKey) throws RemoteException, org.cagrid.gaards.cds.stubs.types.CDSInternalFault, org.cagrid.gaards.cds.stubs.types.DelegationFault, org.cagrid.gaards.cds.stubs.types.PermissionDeniedFault ;

}

