package org.cagrid.gaards.cds.delegated.common;

import java.rmi.RemoteException;

/**
 * Represents a Delegated Credential
 *
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface DelegatedCredentialI {

  public org.cagrid.gaards.cds.common.DelegationIdentifier getDelegatedCredential() throws RemoteException ;

}

