package gov.nih.nci.cagrid.rproteomics.service;

import gov.nih.nci.cagrid.rproteomics.common.RPDataI;
import java.rmi.RemoteException;


/**
 * gov.nih.nci.cagrid.rproteomicsI TODO:DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.0
 */
public class RPDataImpl implements RPDataI {

	public RPDataImpl() {

	}


	public gov.nih.nci.cagrid.cql.CQLQueryResultsType query(gov.nih.nci.cagrid.cql.CQLQueryType query)
		throws RemoteException, gov.nih.nci.cagrid.rproteomics.stubs.MalformedQueryException {
		// TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

}
