package gov.nih.nci.cagrid.tests.common;

import java.rmi.RemoteException;

/** 
 *   This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface BasicAnalyticalServiceI {










     public java.lang.String reverseTranslate(java.lang.String dna) throws RemoteException ;

}

