package gov.nih.nci.cagrid.cadsr.service;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 *  @created by Introduce Toolkit version 1.0
 * 
 */
public class ServiceConfiguration {
	
	private String caCOREServiceURL;
	
	private String threadPoolSize;
	
	private String uml2xmlBindingClassname;
	

	
	public String getCaCOREServiceURL() {
		return caCOREServiceURL;
	}
	
	public void setCaCOREServiceURL(String caCOREServiceURL) {
		this.caCOREServiceURL = caCOREServiceURL;
	}

	
	public String getThreadPoolSize() {
		return threadPoolSize;
	}
	
	public void setThreadPoolSize(String threadPoolSize) {
		this.threadPoolSize = threadPoolSize;
	}

	
	public String getUml2xmlBindingClassname() {
		return uml2xmlBindingClassname;
	}
	
	public void setUml2xmlBindingClassname(String uml2xmlBindingClassname) {
		this.uml2xmlBindingClassname = uml2xmlBindingClassname;
	}

	
}
