package gov.nih.nci.cagrid.cadsr.service;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 *  @created by Introduce Toolkit version 1.0
 * 
 */
public class ServiceConfiguration {
	
	private String caCOREServiceURL;
	

	
	public String getCaCOREServiceURL() {
		return caCOREServiceURL;
	}
	
	public void setCaCOREServiceURL(String caCOREServiceURL) {
		this.caCOREServiceURL = caCOREServiceURL;
	}

	
}
