package gov.nih.nci.cagrid.fqp.service.globus;

import gov.nih.nci.cagrid.fqp.service.FederatedQueryPlanImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class FederatedQueryPlanProviderImpl{
	
	FederatedQueryPlanImpl impl;
	
	public FederatedQueryPlanProviderImpl() throws RemoteException {
		impl = new FederatedQueryPlanImpl();
	}
	

	public gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLResponse processDCQL(gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLRequest params) throws RemoteException {
		gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLResponse boxedResult = new gov.nih.nci.cagrid.fqp.stubs.ProcessDCQLResponse();
		boxedResult.setCQLQueryResultCollection(impl.processDCQL(params.getFederatedQueryPlan().getFederatedQueryPlan()));
		return boxedResult;
	}

}
