<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CDSConfiguration" xmlns="http://schemas.xmlsoap.org/wsdl/" >
	<import location="cds-conf.xsd"/>
	<import location="xsd/database-conf.xsd"/>
</definitions>

