package gov.nih.nci.cagrid.evsgridservice.service.globus;


import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class will have a authorize<methodName> method for each method on this grid service.
 * The method is responsibe for making any authorization callouts required to satisfy the 
 * authorization requirements placed on each method call.  Each method will either simple return
 * apon a successful authorization or will throw an exception apon a failed authorization.
 * 
 * @created by Introduce Toolkit version .99999
 * 
 */
public class EVSGridServiceAuthorization{
	
	
	public EVSGridServiceAuthorization() {
	}
	
	public static String getCallerIdentity() {
		String caller = org.globus.wsrf.security.SecurityManager.getManager().getCaller();
		if ((caller == null) || (caller.equals("<anonymous>"))) {
			return null;
		} else {
			return caller;
		}
	}
	
					
	public static void authorizeGetVocabularyNames() throws RemoteException {
		
		
	}
					
	public static void authorizeGetMetaSources() throws RemoteException {
		
		
	}
					
	public static void authorizeSearchDescLogicConcept() throws RemoteException {
		
		
	}
					
	public static void authorizeSearchMetaThesaurus() throws RemoteException {
		
		
	}
					
	public static void authorizeGetHistoryRecords() throws RemoteException {
		
		
	}
					
	public static void authorizeSearchSourceByCode() throws RemoteException {
		
		
	}
	
	
}
