package gov.nih.nci.cagrid.tests.service.globus;

import gov.nih.nci.cagrid.tests.service.BasicAnalyticalServiceImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class BasicAnalyticalServiceProviderImpl{
	
	BasicAnalyticalServiceImpl impl;
	
	public BasicAnalyticalServiceProviderImpl() throws RemoteException {
		impl = new BasicAnalyticalServiceImpl();
	}
	















	public gov.nih.nci.cagrid.tests.stubs.ReverseTranslateResponse reverseTranslate(gov.nih.nci.cagrid.tests.stubs.ReverseTranslateRequest params) throws RemoteException {
		gov.nih.nci.cagrid.tests.stubs.ReverseTranslateResponse boxedResult = new gov.nih.nci.cagrid.tests.stubs.ReverseTranslateResponse();
		boxedResult.setResponse(impl.reverseTranslate(params.getDna()));
		return boxedResult;
	}

}
