package gov.nih.nci.cagrid.annualdemo.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class MageTranslationServicesImpl extends MageTranslationServicesImplBase {

	
	public MageTranslationServicesImpl() throws RemoteException {
		super();
	}
	

	public void mageToStatML() throws RemoteException {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

	public void mageToMicroArray() throws RemoteException {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

	public void mageToMage() throws RemoteException {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

}

