package gov.nih.nci.cagrid.annualdemo.service;

import gov.nih.nci.cagrid.annualdemo.util.MageToStatml;
import gov.nih.nci.cagrid.data.utilities.CQLObjectResultIterator;
import gov.nih.nci.cagrid.data.utilities.CQLQueryResultsIterator;
import gridextensions.Data;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class MageTranslationServicesImpl extends MageTranslationServicesImplBase {

	
	public MageTranslationServicesImpl() throws RemoteException {
		super();
	}
	

	public gridextensions.Data mageToStatML(gov.nih.nci.cagrid.cqlresultset.CQLQueryResults cQLQueryResultCollection) throws RemoteException {
		int count = cQLQueryResultCollection.getObjectResult().length;
		System.out.println("Got " + count + " Results from caArray");
		
		// hack - Dave: fix this
		cQLQueryResultCollection.setTargetClassname("java.lang.Object");
		
		// get mage
		CQLQueryResultsIterator iter = new CQLQueryResultsIterator(cQLQueryResultCollection, true);
		String mage = (String) iter.next();
		
		//System.out.println(mage);
		try {
			return new MageToStatml().translate(mage);
		} catch (Exception e) {
			e.printStackTrace();
			throw new RemoteException(e.getMessage());
		}
	}

	public edu.columbia.geworkbench.cagrid.microarray.MicroarraySet mageToMicroArray(gov.nih.nci.cagrid.cqlresultset.CQLQueryResults cQLQueryResultCollection) throws RemoteException {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}
}

