package gov.nih.nci.cagrid.data.service.globus;

import gov.nih.nci.cagrid.data.service.EnumerationQueryImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class EnumerationQueryProviderImpl{
	
	EnumerationQueryImpl impl;
	
	public EnumerationQueryProviderImpl() throws RemoteException {
		impl = new EnumerationQueryImpl();
	}
	

	public gov.nih.nci.cagrid.data.enumeration.stubs.EnumerationQueryResponse enumerationQuery(gov.nih.nci.cagrid.data.enumeration.stubs.EnumerationQueryRequest params) throws RemoteException, gov.nih.nci.cagrid.data.faults.QueryProcessingExceptionType, gov.nih.nci.cagrid.data.faults.MalformedQueryExceptionType {
		gov.nih.nci.cagrid.data.enumeration.stubs.EnumerationQueryResponse boxedResult = new gov.nih.nci.cagrid.data.enumeration.stubs.EnumerationQueryResponse();
		boxedResult.setEnumerateResponse(impl.enumerationQuery(params.getCqlQuery().getCQLQuery()));
		return boxedResult;
	}

}
