package gov.nih.nci.cagrid.bdt.service;

import java.rmi.RemoteException;

/** 
 *  gov.nih.nci.cagrid.bdtI
 *  TODO:DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class BulkDataHandlerImpl extends BulkDataHandlerImplBase {

	
	public BulkDataHandlerImpl() throws RemoteException {
		super();
	}
	
	public org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerateResponse createEnumeration() throws RemoteException {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

}

