package gov.nih.nci.cagrid.gridgrouper.stem.service.globus;

import gov.nih.nci.cagrid.gridgrouper.stem.service.GridGrouperStemImpl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class GridGrouperStemProviderImpl{
	
	GridGrouperStemImpl impl;
	
	public GridGrouperStemProviderImpl() throws RemoteException {
		impl = new GridGrouperStemImpl();
	}
	

	public gov.nih.nci.cagrid.gridgrouper.stem.stubs.GetStemNameResponse getStemName(gov.nih.nci.cagrid.gridgrouper.stem.stubs.GetStemNameRequest params) throws RemoteException {
		gov.nih.nci.cagrid.gridgrouper.stem.stubs.GetStemNameResponse boxedResult = new gov.nih.nci.cagrid.gridgrouper.stem.stubs.GetStemNameResponse();
		boxedResult.setResponse(impl.getStemName());
		return boxedResult;
	}

}
