package gov.nih.nci.cagrid.authentication.common;

import java.rmi.RemoteException;

/**
 * The main service context
 *
 * This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface AuthenticationServiceI {

    public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;

  /**
   * Returns a SAMLAssertion about the identity of the caller.
   *
   * @param credential
   * @throws InvalidCredentialFault
   *	Returned if the supplied credentials are invalid.
   * @throws InsufficientAttributeFault
   *	Returned if the attributes returned by the underlying IdP are insufficient for identity federation.
   * @throws AuthenticationProviderFault
   *	Returned if an internal error occurs during this operation.
   */
  public gov.nih.nci.cagrid.authentication.bean.SAMLAssertion authenticate(gov.nih.nci.cagrid.authentication.bean.Credential credential) throws RemoteException, gov.nih.nci.cagrid.authentication.stubs.types.InvalidCredentialFault, gov.nih.nci.cagrid.authentication.stubs.types.InsufficientAttributeFault, gov.nih.nci.cagrid.authentication.stubs.types.AuthenticationProviderFault ;

}
