package gov.nih.nci.cagrid.evsgridservice.common;

import java.rmi.RemoteException;

/**
 * The main EVS grid service.
 *
 * This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface EVSGridServiceI {

    public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;

  /**
   * Returns all the vocabularies present in the Description Logic in caCORE 3.1 EVS service.
   *
   * @return This class will contain the input parameters used by caCORE EVS API to retrieve Description Logic vocabulary names
   */
  public gov.nih.nci.cagrid.evs.service.DescLogicConceptVocabularyName[] getVocabularyNames() throws RemoteException ;

  /**
   * Returns all Metathesaurus Sources contained in the EVS.
   *
   * @return The source is a knowledge base.
   */
  public gov.nih.nci.evs.domain.Source[] getMetaSources() throws RemoteException ;

  /**
   * Searches a valid Vocabulary such as NCI Thesaurus and returns Description Logic concepts that meet the search criteria.
   *
   * @param eVSDescLogicConceptSearchParams
   *	This class will contain the input parameters used by caCORE EVS API to retrieve Description Logic Concept data
   * @return The DescLogicConcept class represents the fundamental vocabulary entity in the NCI Thesaurus. 
   * @throws InvalidInputException
   *	Thrown if invalid inputs are used, such as null or empty concepts or sources.
   */
  public gov.nih.nci.evs.domain.DescLogicConcept[] searchDescLogicConcept(gov.nih.nci.cagrid.evs.service.EVSDescLogicConceptSearchParams eVSDescLogicConceptSearchParams) throws RemoteException, gov.nih.nci.cagrid.evsgridservice.stubs.types.InvalidInputExceptionType ;

  /**
   * Searches NCI meta thesaurus and returns Meta Thesaurus information that meet the search criteria.
   *
   * @param eVSMetaThesaurusSearchParams
   *	This class will contain the input parameters used by caCORE EVS API to retrieve Meta Thesaurus Concepts
   * @return MetaThesaurusConcept is the fundamental vocabulary entity in the NCI MetaThesaurus.
   * @throws InvalidInputException
   *	Thrown if invalid inputs are used, such as null or empty concepts or sources.
   */
  public gov.nih.nci.evs.domain.MetaThesaurusConcept[] searchMetaThesaurus(gov.nih.nci.cagrid.evs.service.EVSMetaThesaurusSearchParams eVSMetaThesaurusSearchParams) throws RemoteException, gov.nih.nci.cagrid.evsgridservice.stubs.types.InvalidInputExceptionType ;

  /**
   * Searches a valid vocabulary in NCI thesaurus for history information.
   *
   * @param eVSHistoryRecordsSearchParams
   *	This class will contain the input parameters used by caCORE EVS API to retrieve History data
   * @return The HistoryRecord holds history information for the specified concept
   * @throws InvalidInputException
   *	Thrown if invalid inputs are used, such as null or empty concepts or sources.
   */
  public gov.nih.nci.evs.domain.HistoryRecord[] getHistoryRecords(gov.nih.nci.cagrid.evs.service.EVSHistoryRecordsSearchParams eVSHistoryRecordsSearchParams) throws RemoteException, gov.nih.nci.cagrid.evsgridservice.stubs.types.InvalidInputExceptionType ;

  /**
   * Searches the Meta Thesaurus based on Source code.
   *
   * @param eVSSourceSearchParams
   *	This class will contain the input parameters used by caCORE EVS API to retrieve Meta Thesaurus Concepts.
   * @return MetaThesaurusConcept is the fundamental vocabulary entity in the NCI MetaThesaurus.
   * @throws InvalidInputException
   *	Thrown if invalid inputs are used, such as null or empty concepts or sources.
   */
  public gov.nih.nci.evs.domain.MetaThesaurusConcept[] searchSourceByCode(gov.nih.nci.cagrid.evs.service.EVSSourceSearchParams eVSSourceSearchParams) throws RemoteException, gov.nih.nci.cagrid.evsgridservice.stubs.types.InvalidInputExceptionType ;

}

