package gov.nih.nci.cagrid.fqp.service;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 *  @created by Introduce Toolkit version 1.0
 * 
 */
public class ServiceConfiguration {
	
	private String threadPoolSize;
	
	private String initialResultLeaseInMinutes;
	

	
	public String getThreadPoolSize() {
		return threadPoolSize;
	}
	
	public void setThreadPoolSize(String threadPoolSize) {
		this.threadPoolSize = threadPoolSize;
	}

	
	public String getInitialResultLeaseInMinutes() {
		return initialResultLeaseInMinutes;
	}
	
	public void setInitialResultLeaseInMinutes(String initialResultLeaseInMinutes) {
		this.initialResultLeaseInMinutes = initialResultLeaseInMinutes;
	}

	
}
