package gov.nih.nci.cagrid.bdt.common;

import java.rmi.RemoteException;

/** 
 *   This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface BDTHandlerServiceI {

	public org.apache.axis.message.addressing.EndpointReferenceType getTransferProvider(bulkdatatransfermetadata.TransferProviderType transferProvider) throws RemoteException ;
public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;

}

