package gov.nih.nci.cagrid.bdt.common;

import java.rmi.RemoteException;

/** 
 *   This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface BulkDataHandlerI {

	public org.xmlsoap.schemas.ws._2004._09.enumeration.PullResponse pullOp(org.xmlsoap.schemas.ws._2004._09.enumeration.Pull pull) throws RemoteException ;

	public org.xmlsoap.schemas.ws._2004._09.enumeration.RenewResponse renewOp(org.xmlsoap.schemas.ws._2004._09.enumeration.Renew renew) throws RemoteException ;

	public org.xmlsoap.schemas.ws._2004._09.enumeration.GetStatusResponse getStatusOp(org.xmlsoap.schemas.ws._2004._09.enumeration.GetStatus status) throws RemoteException ;

	public void releaseOp(org.xmlsoap.schemas.ws._2004._09.enumeration.Release release) throws RemoteException ;

	public org.globus.transfer.AnyXmlType get(org.globus.transfer.EmptyType empty) throws RemoteException ;
public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;
public org.xmlsoap.schemas.ws._2004._09.enumeration.EnumerateResponse createEnumeration() throws RemoteException ;

}

