package gov.nih.nci.cagrid.idp.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;
import org.apache.axis.utils.ClassUtils;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.cagrid.idp.stubs.IDPServicePortType;
import gov.nih.nci.cagrid.idp.stubs.service.IDPServiceAddressingLocator;
import gov.nih.nci.cagrid.idp.common.IDPServiceI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT.
 *
 * This class is not thread safe.  A new instance should be created for any threads using this class.
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.0
 */
public class IDPServiceClient extends ServiceSecurityClient implements IDPServiceI {	
	protected IDPServicePortType portType;
	private Object portTypeMutex;

	public IDPServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public IDPServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	   	initialize();
	}
	
	public IDPServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public IDPServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
		initialize();
	}
	
	private void initialize() throws RemoteException {
	    this.portTypeMutex = new Object();
		this.portType = createPortType();
	}

	private IDPServicePortType createPortType() throws RemoteException {

		IDPServiceAddressingLocator locator = new IDPServiceAddressingLocator();
		// attempt to load our context sensitive wsdd file
		InputStream resourceAsStream = ClassUtils.getResourceAsStream(getClass(), "client-config.wsdd");
		if (resourceAsStream != null) {
			// we found it, so tell axis to configure an engine to use it
			EngineConfiguration engineConfig = new FileProvider(resourceAsStream);
			// set the engine of the locator
			locator.setEngine(new AxisClient(engineConfig));
		}
		IDPServicePortType port = null;
		try {
			port = locator.getIDPServicePortTypePort(getEndpointReference());
		} catch (Exception e) {
			throw new RemoteException("Unable to locate portType:" + e.getMessage(), e);
		}

		return port;
	}

	public static void usage(){
		System.out.println(IDPServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  IDPServiceClient client = new IDPServiceClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			  
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

    public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException {
      synchronized(portTypeMutex){
        configureStubSecurity((Stub)portType,"getServiceSecurityMetadata");
        gov.nih.nci.cagrid.introduce.security.GetServiceSecurityMetadataRequest params = new gov.nih.nci.cagrid.introduce.security.GetServiceSecurityMetadataRequest();
        gov.nih.nci.cagrid.introduce.security.GetServiceSecurityMetadataResponse boxedResult = portType.getServiceSecurityMetadata(params);
        return boxedResult.getServiceSecurityMetadata();
      }
    }
    public gov.nih.nci.cagrid.dorian.SAMLAssertion login(gov.nih.nci.cagrid.idp.beans.CredentialType credential) throws RemoteException, gov.nih.nci.cagrid.idp.stubs.IdpInternalException, gov.nih.nci.cagrid.idp.stubs.InValidCredentialException, gov.nih.nci.cagrid.idp.stubs.InsufficientAttributeException {
      synchronized(portTypeMutex){
        configureStubSecurity((Stub)portType,"login");
        gov.nih.nci.cagrid.idp.stubs.LoginRequest params = new gov.nih.nci.cagrid.idp.stubs.LoginRequest();
        gov.nih.nci.cagrid.idp.stubs.LoginRequestCredential credentialContainer = new gov.nih.nci.cagrid.idp.stubs.LoginRequestCredential();
        credentialContainer.setCredential(credential);
        params.setCredential(credentialContainer);
        gov.nih.nci.cagrid.idp.stubs.LoginResponse boxedResult = portType.login(params);
        return boxedResult.getSAMLAssertion();
      }
    }

}
