package gov.nih.nci.cagrid.workflow.wms.common;

import gov.nih.nci.cagrid.workflow.wms.stubs.service.WMSInputType;
import gov.nih.nci.cagrid.workflow.wms.stubs.service.WMSOutputType;

import java.rmi.RemoteException;

/** 
 *   This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface WorkflowManagementServiceI {



	     public WMSOutputType runWorkflow(WMSInputType wmsInput) throws RemoteException ;

}

